env:
  CI=false

language: node_js

node_js: 
  - "stable"

sudo: false

addons:
  sonarcloud:
    organization: "wadge" 
    token:
      secure: $SONAR-TOKEN

script:
  - npm run build
  - npm test 
  - sonar-scanner


after_success:

cache:
  directories: